// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {frontend} from '../models';

export function GetSettingData():Promise<models.SettingData>;

export function Greet(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:Array<frontend.FileFilter>):Promise<string>;

export function SetSettingData(arg1:models.SettingData):Promise<void>;
